### ISSUE TITLE
image 태그 관련 제안

### ISSUE THREAD

**Issue by dp-daesung** [eunpk/streamlit#3]
https://github.com/eunpk/streamlit/blob/1efbc466baaed33ac951850a3c8f2f67249a8eaf/docker-compose.yaml#L5C4-L5C4 

ECR만 참조하기보다 Dockerfile 을 정의해서 build에 넣어주는건 어떨까요?

**Comment by dp-daesung** [comment]
Compose.yml 을 아래와 같이 작성 할 수 있습니다.
```yaml
version: "3"
services:
  job:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
    image: blarblar
```
